/* Generated By:JavaCC: Do not edit this line. MiniLengCompilerConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MiniLengCompilerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int tPROGRAMA = 11;
  /** RegularExpression Id. */
  int tPRINCIPIO = 12;
  /** RegularExpression Id. */
  int tFIN = 13;
  /** RegularExpression Id. */
  int tSI = 14;
  /** RegularExpression Id. */
  int tENT = 15;
  /** RegularExpression Id. */
  int tSI_NO = 16;
  /** RegularExpression Id. */
  int tFSI = 17;
  /** RegularExpression Id. */
  int tMQ = 18;
  /** RegularExpression Id. */
  int tFMQ = 19;
  /** RegularExpression Id. */
  int tACCION = 20;
  /** RegularExpression Id. */
  int tPCOMA = 21;
  /** RegularExpression Id. */
  int tCOMA = 22;
  /** RegularExpression Id. */
  int tENTACAR = 23;
  /** RegularExpression Id. */
  int tCARAENT = 24;
  /** RegularExpression Id. */
  int tESCRIBIR = 25;
  /** RegularExpression Id. */
  int tLEER = 26;
  /** RegularExpression Id. */
  int tENTERO = 27;
  /** RegularExpression Id. */
  int tVAR = 28;
  /** RegularExpression Id. */
  int tBOOLEANO = 29;
  /** RegularExpression Id. */
  int tCARACTER = 30;
  /** RegularExpression Id. */
  int tVAL = 31;
  /** RegularExpression Id. */
  int tREF = 32;
  /** RegularExpression Id. */
  int tNI = 33;
  /** RegularExpression Id. */
  int tMAI = 34;
  /** RegularExpression Id. */
  int tMEI = 35;
  /** RegularExpression Id. */
  int tMAYOR = 36;
  /** RegularExpression Id. */
  int tMENOR = 37;
  /** RegularExpression Id. */
  int tIGUAL = 38;
  /** RegularExpression Id. */
  int tNOT = 39;
  /** RegularExpression Id. */
  int tAND = 40;
  /** RegularExpression Id. */
  int tOR = 41;
  /** RegularExpression Id. */
  int tTRUE = 42;
  /** RegularExpression Id. */
  int tFALSE = 43;
  /** RegularExpression Id. */
  int tPAREN_DCHA = 44;
  /** RegularExpression Id. */
  int tPAREN_IZQ = 45;
  /** RegularExpression Id. */
  int tSUMA = 46;
  /** RegularExpression Id. */
  int tRESTA = 47;
  /** RegularExpression Id. */
  int tMUL = 48;
  /** RegularExpression Id. */
  int tDIV = 49;
  /** RegularExpression Id. */
  int tMOD = 50;
  /** RegularExpression Id. */
  int tOPAS = 51;
  /** RegularExpression Id. */
  int tCOR_IZQ = 52;
  /** RegularExpression Id. */
  int tCOR_DCHA = 53;
  /** RegularExpression Id. */
  int DIGITO = 54;
  /** RegularExpression Id. */
  int LETRA = 55;
  /** RegularExpression Id. */
  int COMILLA = 56;
  /** RegularExpression Id. */
  int tCONSTCHAR = 57;
  /** RegularExpression Id. */
  int tCONSTCAD = 58;
  /** RegularExpression Id. */
  int tIDENTIFICADOR = 59;
  /** RegularExpression Id. */
  int tCONSTENTERA = 60;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int COMMENT = 1;
  /** Lexical state. */
  int COMMENT_DOUBLE = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 5>",
    "\"%%\"",
    "\"\\n\"",
    "\"%%\"",
    "<token of kind 9>",
    "<token of kind 10>",
    "\"programa\"",
    "\"principio\"",
    "\"fin\"",
    "\"si\"",
    "\"ent\"",
    "\"si_no\"",
    "\"fsi\"",
    "\"mq\"",
    "\"fmq\"",
    "\"accion\"",
    "\";\"",
    "\",\"",
    "\"entacar\"",
    "\"caraent\"",
    "\"escribir\"",
    "\"leer\"",
    "\"entero\"",
    "\"var\"",
    "\"booleano\"",
    "\"caracter\"",
    "\"val\"",
    "\"ref\"",
    "\"<>\"",
    "\">=\"",
    "\"<=\"",
    "\">\"",
    "\"<\"",
    "\"=\"",
    "\"not\"",
    "\"and\"",
    "\"or\"",
    "\"true\"",
    "\"false\"",
    "\")\"",
    "\"(\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "<tDIV>",
    "\"mod\"",
    "\":=\"",
    "\"[\"",
    "\"]\"",
    "<DIGITO>",
    "<LETRA>",
    "<COMILLA>",
    "<tCONSTCHAR>",
    "<tCONSTCAD>",
    "<tIDENTIFICADOR>",
    "<tCONSTENTERA>",
  };

}
